name: Build C++ Program

on:
  push:
    branches: [branchAutoPackage]
  pull_request:
    branches: [branchAutoPackage]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: sudo apt-get update && sudo apt-get install -y g++ make autoconf automake dpkg-dev debhelper build-essential

      - name: Run Autoreconf
        run: autoreconf --install

      - name: Configure
        run: ./configure

      - name: Compile Program
        run: make

      - name: Build Debian Package
        run: dpkg-buildpackage -us -uc

      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: funca-deb
          path: ../funca_1.0.0_amd64.deb
