name: Build C++ Program

on:
  push:
    branches: [branchAutoPackage]
  pull_request:
    branches: [branchAutoPackage]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: sudo apt-get update && sudo apt-get install -y g++ make autoconf automake dpkg-dev debhelper build-essential

      - name: Run Autoreconf
        run: autoreconf --install

      - name: Configure
        run: ./configure

      - name: Compile Program
        run: make

      - name: Run Unit Tests
        run: make check
